// Date: 6/19/2015 3:10:09 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package lightningmats.items.render;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class GunModel extends ModelBase
{
  //fields
    ModelRenderer Barrel1;
    ModelRenderer Barrel3;
    ModelRenderer Grip1;
    ModelRenderer Sight1;
    ModelRenderer Sight2;
    ModelRenderer Trigger;
    ModelRenderer Magazine1;
    ModelRenderer Barrel2;
    ModelRenderer Grip2;
    ModelRenderer Magazine2;
    ModelRenderer Sight3;
  
  public GunModel()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      Barrel1 = new ModelRenderer(this, 0, 62);
      Barrel1.addBox(0F, 0F, 0F, 12, 1, 1);
      Barrel1.setRotationPoint(0F, -15F, 0.5F);
      Barrel1.setTextureSize(64, 64);
      Barrel1.mirror = true;
      setRotation(Barrel1, 0F, 0F, 0F);
      Barrel3 = new ModelRenderer(this, 0, 60);
      Barrel3.addBox(0F, 0F, 0F, 11, 1, 1);
      Barrel3.setRotationPoint(0.3F, -14.3F, 0.3F);
      Barrel3.setTextureSize(64, 64);
      Barrel3.mirror = true;
      setRotation(Barrel3, 0F, 0F, 0F);
      Grip1 = new ModelRenderer(this, 0, 51);
      Grip1.addBox(0F, 0F, 0F, 2, 7, 1);
      Grip1.setRotationPoint(10F, -14.5F, 0.3F);
      Grip1.setTextureSize(64, 64);
      Grip1.mirror = true;
      setRotation(Grip1, 0F, 0F, -0.2443461F);
      Sight1 = new ModelRenderer(this, 0, 42);
      Sight1.addBox(0F, 0F, 0F, 2, 1, 0);
      Sight1.setRotationPoint(9F, -14.2F, 0.6F);
      Sight1.setTextureSize(64, 64);
      Sight1.mirror = true;
      setRotation(Sight1, 0F, 0F, -0.6981317F);
      Sight2 = new ModelRenderer(this, 0, 42);
      Sight2.addBox(0F, 0F, 0F, 2, 1, 0);
      Sight2.setRotationPoint(9F, -14.2F, 1.4F);
      Sight2.setTextureSize(64, 64);
      Sight2.mirror = true;
      setRotation(Sight2, 0F, 0F, -0.6981317F);
      Trigger = new ModelRenderer(this, 0, 44);
      Trigger.addBox(0F, 0F, 0F, 1, 1, 1);
      Trigger.setRotationPoint(10F, -13.3F, 0.4666667F);
      Trigger.setTextureSize(64, 64);
      Trigger.mirror = true;
      setRotation(Trigger, 0F, 0F, 0F);
      Magazine1 = new ModelRenderer(this, 0, 37);
      Magazine1.addBox(0F, 0F, 0F, 2, 0, 1);
      Magazine1.setRotationPoint(11.2F, -7.5F, 0.3F);
      Magazine1.setTextureSize(64, 64);
      Magazine1.mirror = true;
      setRotation(Magazine1, 0F, 0F, -0.2617994F);
      Barrel2 = new ModelRenderer(this, 0, 60);
      Barrel2.addBox(0F, 0F, 0F, 11, 1, 1);
      Barrel2.setRotationPoint(0.3F, -14.3F, 0.7F);
      Barrel2.setTextureSize(64, 64);
      Barrel2.mirror = true;
      setRotation(Barrel2, 0F, 0F, 0F);
      Grip2 = new ModelRenderer(this, 0, 51);
      Grip2.addBox(0F, 0F, 0F, 2, 7, 1);
      Grip2.setRotationPoint(10F, -14.5F, 0.7F);
      Grip2.setTextureSize(64, 64);
      Grip2.mirror = true;
      setRotation(Grip2, 0F, 0F, -0.2443461F);
      Magazine2 = new ModelRenderer(this, 0, 37);
      Magazine2.addBox(0F, 0F, 0F, 2, 0, 1);
      Magazine2.setRotationPoint(11.2F, -7.5F, 0.7F);
      Magazine2.setTextureSize(64, 64);
      Magazine2.mirror = true;
      setRotation(Magazine2, 0F, 0F, -0.2617994F);
      Sight3 = new ModelRenderer(this, 0, 0);
      Sight3.addBox(0F, -2F, 0F, 1, 1, 0);
      Sight3.setRotationPoint(0F, -15.3F, 1.033333F);
      Sight3.setTextureSize(64, 64);
      Sight3.mirror = true;
      setRotation(Sight3, 0F, 0F, 1.570796F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Barrel1.render(f5);
    Barrel3.render(f5);
    Grip1.render(f5);
    Sight1.render(f5);
    Sight2.render(f5);
    Trigger.render(f5);
    Magazine1.render(f5);
    Barrel2.render(f5);
    Grip2.render(f5);
    Magazine2.render(f5);
    Sight3.render(f5);
  }
  
  public void renderModel(float f5){
	  
	  Barrel1.render(f5);
	    Barrel3.render(f5);
	    Grip1.render(f5);
	    Sight1.render(f5);
	    Sight2.render(f5);
	    Trigger.render(f5);
	    Magazine1.render(f5);
	    Barrel2.render(f5);
	    Grip2.render(f5);
	    Magazine2.render(f5);
	    Sight3.render(f5);
	  
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity ent)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, ent);
  }

}
